FROM gradle:8-jdk21-alpine AS build
WORKDIR /app
COPY budgetprocess/ .
RUN ./gradlew bootJar -x test --no-daemon

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-Xmx192m", "-Xms96m", "-jar", "app.jar"]
